### ISSUE TITLE
Problem with animating the node's color change

### ISSUE THREAD

**Issue by vldygrf** [maxgribov/Spine#57]
This is a useful framework for me, I plan to use it in my project. Thanks!

I found a problem when animating the node's color change. Animation duration is not taken into account. I would suggest such a change (line #252, Animation.swift):

`let delta = timing Function(Float(time) / Float(duration))`

After this fix, everything works correctly for me.

**Comment by maxgribov** [comment]
Can you create pull request?

**Comment by vldygrf** [comment]
remote: Permission to maxgribov/Spine.git denied to vldygrf.
Seems I don't have permissions to do it.

**Comment by maxgribov** [comment]
Are you sure you trying to make pull request from your fork? Because I don't see any restrictions on pull requests in the repo's settings.

Please, check this to make sure you are on a right way: 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by vldygrf** [comment]
The problem was on my side in the outdated token. I made a pull request.
